apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: espvc
  namespace: elasticsearch
spec:
  accessMode: ReadWriteOnce
  selector
    matchLabels:
      app: elasticsearch
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  volumeName: espv
      
  
  
  
